<?php

declare(strict_types=1);

use Database\Seeders\RolePermissionSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Modules\VideoEdits\Domain\Enums\VideoEditMode;
use Modules\VideoEdits\Infrastructure\Persistence\Eloquent\Models\VideoEditEloquentModel;
use Modules\VideoEdits\Tests\Support\VideoEditTestUsers;

uses(RefreshDatabase::class);

beforeEach(function (): void {
    $this->seed(RolePermissionSeeder::class);
});

/**
 * @param  array<string, mixed>  $overrides
 * @return array<string, mixed>
 */
function aiEditPayload(array $overrides = []): array
{
    return array_replace([
        'mode' => 'ai_edit',
        'speech_cleanup' => ['enabled' => true],
        'ai_edit' => ['enabled' => true, 'consented' => true],
        'sources' => [
            ['position' => 1, 'file_name' => 'take-1.mp4', 'mime_type' => 'video/mp4', 'size_bytes' => 10_000_000],
        ],
    ], $overrides);
}

it('accepts an AI edit now that V3 has shipped', function (): void {
    $this->actingAs(VideoEditTestUsers::editor())
        ->postJson('/data/admin/video-edits', aiEditPayload())
        ->assertCreated();

    expect(VideoEditEloquentModel::query()->latest('id')->firstOrFail()->mode)
        ->toBe(VideoEditMode::AiEdit);
});

it('records when consent was given, not merely that it was', function (): void {
    $this->actingAs(VideoEditTestUsers::editor())
        ->postJson('/data/admin/video-edits', aiEditPayload())
        ->assertCreated();

    $edit = VideoEditEloquentModel::query()->latest('id')->firstOrFail();

    expect($edit->ai_consent_at)->not->toBeNull()
        ->and($edit->parameters['ai_edit']['consented'])->toBeTrue();
});

it('refuses an AI edit without consent', function (): void {
    $this->actingAs(VideoEditTestUsers::editor())
        ->postJson('/data/admin/video-edits', aiEditPayload([
            'ai_edit' => ['enabled' => true, 'consented' => false],
        ]))
        ->assertStatus(422)
        ->assertJsonValidationErrors('ai_edit.consented');
});

it('refuses an AI edit without speech cleanup, which supplies the transcript', function (): void {
    $this->actingAs(VideoEditTestUsers::editor())
        ->postJson('/data/admin/video-edits', aiEditPayload([
            'speech_cleanup' => ['enabled' => false],
        ]))
        ->assertStatus(422)
        ->assertJsonValidationErrors('speech_cleanup.enabled');
});

it('issues a separate upload target for the script', function (): void {
    $response = $this->actingAs(VideoEditTestUsers::editor())
        ->postJson('/data/admin/video-edits', aiEditPayload([
            'ai_edit' => [
                'enabled' => true,
                'consented' => true,
                'script' => ['file_name' => 'Video 6.1.pdf', 'mime_type' => 'application/pdf', 'size_bytes' => 250_000],
            ],
        ]))
        ->assertCreated();

    $response->assertJsonPath('script_upload.position', 0);
    expect($response->json('script_upload.upload_url'))->toBeString();

    $edit = VideoEditEloquentModel::query()->latest('id')->firstOrFail();

    expect($edit->script)->not->toBeNull()
        ->and($edit->script->original_name)->toBe('Video 6.1.pdf')
        ->and($edit->script->extension)->toBe('pdf')
        // The key is generated by us, never taken from the client (FR-19).
        ->and($edit->script->storage_path)->toContain($edit->uuid);
});

it('rejects a script that is not markdown or PDF', function (): void {
    $this->actingAs(VideoEditTestUsers::editor())
        ->postJson('/data/admin/video-edits', aiEditPayload([
            'ai_edit' => [
                'enabled' => true,
                'consented' => true,
                'script' => ['file_name' => 'script.docx', 'mime_type' => 'application/pdf', 'size_bytes' => 1_000],
            ],
        ]))
        ->assertStatus(422)
        ->assertJsonValidationErrors('ai_edit.script.file_name');
});

it('prohibits the AI block on a merge, which does no content analysis', function (): void {
    $this->actingAs(VideoEditTestUsers::editor())
        ->postJson('/data/admin/video-edits', aiEditPayload([
            'mode' => 'merge',
            'speech_cleanup' => null,
            'sources' => [
                ['position' => 1, 'file_name' => 'a.mp4', 'mime_type' => 'video/mp4', 'size_bytes' => 1_000],
                ['position' => 2, 'file_name' => 'b.mp4', 'mime_type' => 'video/mp4', 'size_bytes' => 1_000],
            ],
        ]))
        ->assertStatus(422)
        ->assertJsonValidationErrors('ai_edit');
});

it('requires the AI block when the mode is ai_edit', function (): void {
    $this->actingAs(VideoEditTestUsers::editor())
        ->postJson('/data/admin/video-edits', aiEditPayload(['ai_edit' => null]))
        ->assertStatus(422)
        ->assertJsonValidationErrors('ai_edit');
});

it('caps the instructions so one paste cannot blow the context window', function (): void {
    $this->actingAs(VideoEditTestUsers::editor())
        ->postJson('/data/admin/video-edits', aiEditPayload([
            'ai_edit' => ['enabled' => true, 'consented' => true, 'instructions' => str_repeat('a', 20_001)],
        ]))
        ->assertStatus(422)
        ->assertJsonValidationErrors('ai_edit.instructions');
});
